import type { PlannerCompletion, PlannerRole } from "./contracts";
import { TripError } from "../trip-state/model";

const cookieName="beacon-session";
function ownerSession(request:Request,create=false){const existing=request.headers.get("cookie")?.split(";").map(c=>c.trim()).find(c=>c.startsWith(`${cookieName}=`))?.slice(cookieName.length+1);const token=existing&&/^[a-f0-9]{64}$/.test(existing)?existing:create?randomBytes(32).toString("hex"):undefined;if(!token)throw new TripError("AUTH_REQUIRED","Start a trip in this browser first",401);return{owner:createHash("sha256").update(token).digest("hex"),cookie:existing===token?undefined:`${cookieName}=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400${new URL(request.url).protocol==="https:"?"; Secure":""}`};}
function sameOrigin(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new TripError("ORIGIN_REJECTED","Cross-origin mutation rejected",403);}
async function requestBody(request:Request){if(!request.headers.get("content-type")?.includes("application/json"))throw new TripError("JSON_REQUIRED","Use application/json",415);if(Number(request.headers.get("content-length")??0)>16384)throw new TripError("BODY_TOO_LARGE","Request too large",413);const text=await request.text();if(Buffer.byteLength(text)>16384)throw new TripError("BODY_TOO_LARGE","Request too large",413);try{const value=text?JSON.parse(text):{};if(!value||typeof value!=="object"||Array.isArray(value))throw new Error();return value as Record<string,unknown>;}catch{throw new TripError("INVALID_JSON","JSON object required",400);}}
function requireBearer(request:Request,expected:string){const actual=Buffer.from(request.headers.get("authorization")??""),wanted=Buffer.from(`Bearer ${expected}`);if(actual.length!==wanted.length||!timingSafeEqual(actual,wanted))throw new TripError("UNAUTHORIZED","Unauthorized",401);}
function noStoreJson(value:unknown,status=200,cookie?:string){return Response.json(value,{status,headers:{"Cache-Control":"no-store",...(cookie?{"Set-Cookie":cookie}:{})}});}
async function handleTripHttp(fn:()=>Promise<Response>){try{return await fn();}catch(error){if(error instanceof TripError)return noStoreJson({error:{code:error.code,message:error.message}},error.status);return noStoreJson({error:{code:"SERVICE_UNAVAILABLE",message:"Planner service unavailable; please try again"}},503);}}
function configured(){if(!["deterministic","codex_laptop"].includes(process.env.BEACON_PLANNER_MODE??""))throw new TripError("SERVICE_NOT_CONFIGURED","Planning is not enabled",503);}
function laptopEnabled(){if(process.env.BEACON_PLANNER_MODE!=="codex_laptop")throw new TripError("SERVICE_NOT_CONFIGURED","Laptop planning is not enabled",503);}
function worker(request:Request){laptopEnabled();const token=process.env.BEACON_PLANNER_WORKER_TOKEN;if(!token||token.length<32)throw new TripError("SERVICE_NOT_CONFIGURED","Planner worker authorization is not configured",503);requireBearer(request,token);}
function plannerError(error:unknown):never{
 if(error instanceof TripError)throw error;
 const code=error instanceof Error?error.message:"SERVICE_UNAVAILABLE";
 const allowed=["PAIRING_REQUIRED","PAIRING_INVALID","INVALID_INPUT","INVALID_OUTPUT","STALE_LEASE","STALE_STAGE","STALE_SNAPSHOT","COMPLETION_CONFLICT","PLANNING_ACTIVE","QUEUE_FULL","PAIRING_LIMIT","WORKER_LIMIT","TRIP_TERMINAL"];
 const safe=allowed.includes(code)?code:"SERVICE_UNAVAILABLE";
 const status=safe==="PAIRING_REQUIRED"?401:safe==="PAIRING_INVALID"||safe.startsWith("INVALID")?400:["STALE_LEASE","STALE_STAGE","STALE_SNAPSHOT","COMPLETION_CONFLICT","PLANNING_ACTIVE","TRIP_TERMINAL"].includes(safe)?409:["QUEUE_FULL","PAIRING_LIMIT","WORKER_LIMIT"].includes(safe)?429:503;
 throw new TripError(safe==="PAIRING_INVALID"?"PAIR_CODE_INVALID":safe,"Planner request could not be completed",status);
}
function exact(value:Record<string,unknown>,keys:string[]){if(Object.keys(value).length!==keys.length||keys.some(k=>!Object.hasOwn(value,k)))throw new TripError("INVALID_INPUT","Unexpected request fields",400);}

export function pairPlanner(request:Request){return handleTripHttp(async()=>{try{laptopEnabled();sameOrigin(request);const input=await requestBody(request);exact(input,["code"]);const session=ownerSession(request,true);const{getPlannerRuntime}=await import("./runtime");await getPlannerRuntime().queue.pair(session.owner,input.code);return noStoreJson({paired:true},200,session.cookie);}catch(e){plannerError(e);}});}
export function createPairing(request:Request){return handleTripHttp(async()=>{try{worker(request);const input=await requestBody(request);exact(input,[]);const{getPlannerRuntime}=await import("./runtime");return noStoreJson({code:await getPlannerRuntime().queue.createPairing()});}catch(e){plannerError(e);}});}
export function startPlanning(request:Request,id:string){return handleTripHttp(async()=>{try{configured();sameOrigin(request);const input=await requestBody(request);exact(input,[]);const session=ownerSession(request);const{activePlanner}=await import("./runtime");return noStoreJson(await activePlanner().start(session.owner,id),202);}catch(e){plannerError(e);}});}
export function claimPlanner(request:Request){return handleTripHttp(async()=>{try{worker(request);const input=await requestBody(request);exact(input,["workerId","roles"]);if(typeof input.workerId!=="string"||!Array.isArray(input.roles))throw new Error("INVALID_INPUT");const{getPlannerRuntime}=await import("./runtime");const claim=await getPlannerRuntime().queue.claim(input.workerId,input.roles as PlannerRole[]);return claim?noStoreJson(claim):new Response(null,{status:204,headers:{"Cache-Control":"no-store"}});}catch(e){plannerError(e);}});}
export function heartbeatPlanner(request:Request){return handleTripHttp(async()=>{try{worker(request);const input=await requestBody(request);exact(input,["workerId","jobId","leaseId","authState","model"]);const{getPlannerRuntime}=await import("./runtime");await getPlannerRuntime().queue.heartbeat(String(input.workerId),input.jobId===null?null:String(input.jobId),input.leaseId===null?null:String(input.leaseId),input.authState as "online"|"auth_required"|"rate_limited",String(input.model));return noStoreJson({accepted:true});}catch(e){plannerError(e);}});}
export function completePlanner(request:Request){return handleTripHttp(async()=>{try{worker(request);const input=await requestBody(request);const{getPlannerRuntime}=await import("./runtime");await getPlannerRuntime().planner.complete(input as unknown as PlannerCompletion);return noStoreJson({accepted:true},202);}catch(e){plannerError(e);}});}
export function tickPlanner(request:Request){return handleTripHttp(async()=>{try{worker(request);const input=await requestBody(request);exact(input,[]);const{getPlannerRuntime}=await import("./runtime");return noStoreJson(await getPlannerRuntime().planner.tick());}catch(e){plannerError(e);}});}
export function readActivity(request:Request,id:string){return handleTripHttp(async()=>{const owner=ownerSession(request).owner;const[{getRuntime},{getActivityRuntime}]=await Promise.all([import("../trip-state/runtime"),import("../agent-activity/runtime")]);await getRuntime().agent.read(id,owner);const url=new URL(request.url);if([...url.searchParams.keys()].some(k=>k!=="after"))throw new TripError("INVALID_CURSOR","Invalid activity cursor",400);const raw=url.searchParams.get("after")??"0";if(!/^\d{1,12}$/.test(raw))throw new TripError("INVALID_CURSOR","Invalid activity cursor",400);return noStoreJson(await getActivityRuntime().read(id,Number(raw)));});}
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
