import { randomBytes, randomUUID } from "node:crypto";
import type { JsonStore } from "./store";
import type { Fact, PlannerCompletion, PlannerJob, PlannerRole, PlanningView } from "./contracts";
import { digest, exact, validateOutput } from "./validation";

export type StoredJob = PlannerJob & { owner:string; tripId:string; runId:string; state:"queued"|"leased"|"succeeded"|"failed"|"expired"; attempt:number; leaseId?:string; workerId?:string; leaseUntil?:number; result?:PlannerCompletion; resultHash?:string };
export type PlanningRun = { id:string; tripId:string; owner:string; createdAt:number; updatedAt:number; phase:PlanningView["phase"]; jobId:string; snapshotId:string; facts?:Fact[]; selectedPlanId?:string; selectionExpiresAt?:number; explanation?:string; model?:string; explanationSource:PlanningView["explanationSource"]; messageCode:string; stageToken?:string; stageUntil?:number };
export type PlannerState = { pairing:Record<string,number>; paired:Record<string,number>; jobs:Record<string,StoredJob>; runs:Record<string,PlanningRun>; workers:Record<string,{seenAt:number;authState:"online"|"auth_required"|"rate_limited";model:string}> };
export const emptyPlannerState=():PlannerState=>({pairing:{},paired:{},jobs:{},runs:{},workers:{}});
const roles:PlannerRole[]=["student-intent","research-intent","student-explanation"];
const models=["gpt-5.6-sol","gpt-5.6-terra"];
const identifier=(v:unknown)=>typeof v==="string"&&/^[a-zA-Z0-9_.:-]{1,128}$/.test(v);
const active=(run:PlanningRun)=>!["ready","needs_input","unavailable"].includes(run.phase);
export function publicJob(job:StoredJob):PlannerJob{const{version,jobId,role,snapshotId,inputHash,issuedAt,expiresAt,input}=job;return{version,jobId,role,snapshotId,inputHash,issuedAt,expiresAt,input};}

export class PlannerQueue{
 constructor(readonly state:JsonStore<PlannerState>,readonly now:()=>number=Date.now){}
 private prune(s:PlannerState){const now=this.now();for(const[k,t]of Object.entries(s.pairing))if(t<=now)delete s.pairing[k];for(const[k,t]of Object.entries(s.paired))if(t<=now)delete s.paired[k];for(const[k,j]of Object.entries(s.jobs))if(Date.parse(j.issuedAt)<now-86400000)delete s.jobs[k];for(const[k,r]of Object.entries(s.runs))if(r.updatedAt<now-86400000)delete s.runs[k];for(const[k,w]of Object.entries(s.workers))if(w.seenAt<now-120000)delete s.workers[k];}
 private makeJob(owner:string,tripId:string,runId:string,role:PlannerRole,snapshotId:string,input:Record<string,unknown>):StoredJob{if(!roles.includes(role)||JSON.stringify(input).length>20000)throw new Error("INVALID_INPUT");return{version:"beacon-planner-job-v1",jobId:randomUUID(),role,snapshotId,inputHash:digest(input),issuedAt:new Date(this.now()).toISOString(),expiresAt:new Date(this.now()+90000).toISOString(),input:structuredClone(input),owner,tripId,runId,state:"queued",attempt:0};}
 async createPairing(){const code=randomBytes(16).toString("hex");await this.state.update(s=>{this.prune(s);if(Object.keys(s.pairing).length>=20)throw new Error("PAIRING_LIMIT");s.pairing[digest(code)]=this.now()+600000;});return code;}
 async pair(owner:string,code:unknown){if(!identifier(owner)||typeof code!=="string"||!/^[a-f0-9]{32}$/.test(code))throw new Error("PAIRING_INVALID");await this.state.update(s=>{this.prune(s);const k=digest(code);if(!s.pairing[k])throw new Error("PAIRING_INVALID");delete s.pairing[k];s.paired[owner]=this.now()+7200000;});}
 async requirePair(owner:string){if(((await this.state.read()).paired[owner]??0)<=this.now())throw new Error("PAIRING_REQUIRED");}
 async enqueue(owner:string,tripId:string,role:PlannerRole,snapshotId:string,input:Record<string,unknown>){return this.state.update(s=>{this.prune(s);if((s.paired[owner]??0)<=this.now())throw new Error("PAIRING_REQUIRED");const inputHash=digest(input);const existing=Object.values(s.jobs).find(j=>j.tripId===tripId&&j.snapshotId===snapshotId&&j.role===role&&j.inputHash===inputHash&&["queued","leased"].includes(j.state)&&Date.parse(j.expiresAt)>this.now());if(existing)return publicJob(existing);if(Object.values(s.jobs).filter(j=>["queued","leased"].includes(j.state)&&Date.parse(j.expiresAt)>this.now()).length>=20)throw new Error("QUEUE_FULL");const job=this.makeJob(owner,tripId,randomUUID(),role,snapshotId,input);s.jobs[job.jobId]=job;return publicJob(job);});}
 async startRun(owner:string,tripId:string,snapshotId:string,input:Record<string,unknown>){return this.state.update(s=>{this.prune(s);if((s.paired[owner]??0)<=this.now())throw new Error("PAIRING_REQUIRED");const existing=Object.values(s.runs).find(r=>r.owner===owner&&active(r));if(existing){if(existing.tripId!==tripId)throw new Error("PLANNING_ACTIVE");if(existing.snapshotId!==snapshotId)throw new Error("STALE_SNAPSHOT");return{runId:existing.id,phase:existing.phase};}if(Object.values(s.jobs).filter(j=>["queued","leased"].includes(j.state)&&Date.parse(j.expiresAt)>this.now()).length>=20)throw new Error("QUEUE_FULL");const runId=randomUUID(),job=this.makeJob(owner,tripId,runId,"student-intent",snapshotId,input);s.jobs[job.jobId]=job;s.runs[tripId]={id:runId,tripId,owner,createdAt:this.now(),updatedAt:this.now(),phase:"understanding",jobId:job.jobId,snapshotId,explanationSource:"none",messageCode:"PLANNER_UNDERSTANDING"};return{runId,phase:"understanding" as const};});}
 async claim(workerId:string,requestedRoles:PlannerRole[]=roles){if(!identifier(workerId)||!Array.isArray(requestedRoles)||!requestedRoles.length||requestedRoles.some(r=>!roles.includes(r))||new Set(requestedRoles).size!==requestedRoles.length)throw new Error("INVALID_INPUT");return this.state.update(s=>{this.prune(s);for(const j of Object.values(s.jobs)){if(!requestedRoles.includes(j.role)||!["queued","leased"].includes(j.state))continue;if(Date.parse(j.expiresAt)<=this.now()||(s.paired[j.owner]??0)<=this.now()){j.state="expired";continue;}if(j.state==="leased"&&(j.leaseUntil??0)>this.now())continue;if(j.attempt>=2){j.state="failed";continue;}j.state="leased";j.workerId=workerId;j.leaseId=randomUUID();j.leaseUntil=Math.min(this.now()+30000,Date.parse(j.expiresAt));j.attempt++;return{job:publicJob(j),leaseId:j.leaseId,attempt:j.attempt};}return null;});}
 async heartbeat(workerId:string,jobId:string|null,leaseId:string|null,authState:"online"|"auth_required"|"rate_limited",model:string){if(!identifier(workerId)||!["online","auth_required","rate_limited"].includes(authState)||!models.includes(model))throw new Error("INVALID_INPUT");await this.state.update(s=>{this.prune(s);if(Object.keys(s.workers).length>=5&&!s.workers[workerId])throw new Error("WORKER_LIMIT");s.workers[workerId]={seenAt:this.now(),authState,model};if(jobId){const j=s.jobs[jobId];if(!j||j.state!=="leased"||j.workerId!==workerId||j.leaseId!==leaseId||(j.leaseUntil??0)<=this.now()||Date.parse(j.expiresAt)<=this.now())throw new Error("STALE_LEASE");j.leaseUntil=Math.min(this.now()+30000,Date.parse(j.expiresAt));}else if(leaseId!==null)throw new Error("INVALID_INPUT");});}
 async complete(input:PlannerCompletion){const v=exact(input,["version","jobId","leaseId","attempt","snapshotId","inputHash","model","outcome","output","errorCode"]);if(v.version!=="beacon-planner-result-v1"||!identifier(v.jobId)||!identifier(v.leaseId)||!models.includes(String(v.model))||!["succeeded","failed"].includes(String(v.outcome))||!Number.isSafeInteger(v.attempt)||JSON.stringify(input).length>32768)throw new Error("INVALID_OUTPUT");return this.state.update(s=>{this.prune(s);const j=s.jobs[input.jobId];if(!j||(s.paired[j.owner]??0)<=this.now())throw new Error("STALE_LEASE");const hash=digest(input);if(j.resultHash){if(j.resultHash!==hash)throw new Error("COMPLETION_CONFLICT");return;}if(j.state!=="leased"||j.leaseId!==input.leaseId||j.attempt!==input.attempt||(j.leaseUntil??0)<=this.now()||Date.parse(j.expiresAt)<=this.now()||j.snapshotId!==input.snapshotId||j.inputHash!==input.inputHash)throw new Error("STALE_LEASE");if(input.outcome==="succeeded"){validateOutput(j.role,input.output);if(input.errorCode!==null)throw new Error("INVALID_OUTPUT");}else if(input.output!==null||!["AUTH_REQUIRED","RATE_LIMITED","TIMEOUT","INVALID_OUTPUT","MODEL_UNAVAILABLE"].includes(input.errorCode??""))throw new Error("INVALID_OUTPUT");j.state=input.outcome;j.result=structuredClone(input);j.resultHash=hash;});}
 async readJob(id:string){return(await this.state.read()).jobs[id];}
 async readRun(tripId:string){return(await this.state.read()).runs[tripId];}
 async claimReadyStage(){return this.state.update(s=>{this.prune(s);for(const r of Object.values(s.runs)){const j=s.jobs[r.jobId];if(j&&["queued","leased"].includes(j.state)&&(Date.parse(j.expiresAt)<=this.now()||(s.paired[j.owner]??0)<=this.now()))j.state="expired";if(!active(r)||!j||!["succeeded","failed","expired"].includes(j.state)||(r.stageUntil??0)>this.now())continue;r.stageToken=randomUUID();r.stageUntil=this.now()+90000;r.updatedAt=this.now();return{run:structuredClone(r),job:structuredClone(j),stageToken:r.stageToken};}return null;});}
 async setRunPhase(tripId:string,runId:string,token:string,phase:PlanningView["phase"],messageCode:string){await this.state.update(s=>{const r=s.runs[tripId];if(!r||r.id!==runId||r.stageToken!==token||(r.stageUntil??0)<=this.now())throw new Error("STALE_STAGE");r.phase=phase;r.messageCode=messageCode;r.updatedAt=this.now();});}
 async queueExplanation(run:PlanningRun,token:string,selection:{snapshotId:string;selectedPlanId:string;expiresAt:number;facts:Fact[]}){return this.state.update(s=>{const r=s.runs[run.tripId];if(!r||r.id!==run.id||r.stageToken!==token||(r.stageUntil??0)<=this.now())throw new Error("STALE_STAGE");const input={snapshotId:selection.snapshotId,selectedPlanId:selection.selectedPlanId,facts:selection.facts};const job=this.makeJob(run.owner,run.tripId,run.id,"student-explanation",selection.snapshotId,input);s.jobs[job.jobId]=job;Object.assign(r,{phase:"explaining",messageCode:"PLANNER_EXPLAINING",jobId:job.jobId,snapshotId:selection.snapshotId,selectedPlanId:selection.selectedPlanId,selectionExpiresAt:selection.expiresAt,facts:structuredClone(selection.facts),explanation:undefined,model:undefined,explanationSource:"none",updatedAt:this.now(),stageToken:undefined,stageUntil:undefined});return publicJob(job);});}
 async finishRun(run:PlanningRun,token:string,result:{phase:PlanningView["phase"];messageCode:string;explanation?:string;model?:string;explanationSource?:PlanningView["explanationSource"]}){await this.state.update(s=>{const r=s.runs[run.tripId];if(!r||r.id!==run.id||r.stageToken!==token||(r.stageUntil??0)<=this.now())throw new Error("STALE_STAGE");Object.assign(r,result,{updatedAt:this.now(),stageToken:undefined,stageUntil:undefined});});}
 async invalidate(tripId:string){await this.state.update(s=>{delete s.runs[tripId];for(const[k,j]of Object.entries(s.jobs))if(j.tripId===tripId)delete s.jobs[k];});}
 async worker(){const workers=Object.values((await this.state.read()).workers).sort((a,b)=>b.seenAt-a.seenAt),w=workers[0];return w&&w.seenAt>this.now()-35000?{state:w.authState,model:w.model}:{state:"offline" as const,model:undefined};}
}
